kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: build
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker build -t dancheg97.ru/$DRONE_REPO:latest -t dancheg97.ru/$DRONE_REPO:$(date +"%m-%d-%y") .

  - name: push
    image: docker
    environment:
      PASS:
        from_secret: PASS
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker login -u dancheg97 -p $PASS dancheg97.ru
      - docker push dancheg97.ru/$DRONE_REPO:latest
      - docker push dancheg97.ru/$DRONE_REPO:$(date +"%m-%d-%y")
