kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: lint and test
    image: golangci/golangci-lint
    commands: 
      - golangci-lint run
      - go test ./...

  - name: dockerize, build and push to registry
    image: docker
    environment:
      PASS:
        from_secret: PASS
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker build -t dancheg97.ru/$DRONE_REPO:latest -t dancheg97.ru/$DRONE_REPO:$(date +"%m-%d-%y") .
      - docker login -u dancheg97 -p $PASS dancheg97.ru
      - docker push dancheg97.ru/$DRONE_REPO:latest
      - docker push dancheg97.ru/$DRONE_REPO:$(date +"%m-%d-%y")

  - name: github mirror push
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote: ssh://git@github.com/dancheg97/gen-tools.git
      force: false
      commit: true
      ssh_key:
        from_secret: SSHKEY
