kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: lint, test and build
    image: dancheg97.ru/dancheg97/gen-tools:latest
    commands:
      - if [[ $(gofumpt -d . | wc -c) -ne 0 ]]; then exit 1; fi 
      - golangci-lint run
      - go test ./...
      - go build

  - name: github mirror push
    image: appleboy/drone-git-push
    settings:
      branch: master
      remote: ssh://git@github.com/dancheg97/gen-tools.git
      force: false
      commit: true
      ssh_key:
        from_secret: SSHKEY
