package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   "gen-tools",
	Short: "🧰 Tool for generating project templates written in go.",
	Long: `🧰 CLI Tool for generating different project modules for templating
complex systems with ease.

	LICENSE

	gen-tools  Copyright (C) 2023  Dancheg97
	
	This program comes with ABSOLUTELY NO WARRANTY; for details 'use -h flag'.
	This is free software, and you are welcome to redistribute it
	under certain conditions; watch license in repo for details.

📃 Options you can specify under 'gen' command:

- drone - includes drone.yml template for project CI-CD
- mit - adds MIT license to project
- gpl - adds GPLv3 license to project
- make - adds Makefile to project
- pkgbuild - arch format PKGBUILD for packaging to AUR
- lego - generates templates of commands for lego, to simplify process of obtaining certificates

Compose file options:

- compose-nginx - adds nginx to your compose file, and generates template of config in directory (reuses certificates generated by lego)
- compose-postgres - adds postgres to compose file, and goose tool for migrations aswell
- compose-redis - adds redis to compose
- compose-nats - adds single nats node to compose, and nats-ui for visualization
- compose-gitea - adds gitea with some predefined parameters and configuartion files, additional themes, description, logo
- compose-drone - adds drone server and runner to compose, with predifined parameters to connect to gitea
- compose-pacman - adds self-hosted pacman repository for arch packages
- compose-pocketbase - adds pocketbase template to compose (self-hosted real-time backend)
- compose-mkdocs - adds mkdocs with theme, custom css and some preconfigured stuff

Go code options:

- go-cli - includes cobra and viper
- go-lint - includes golanglint-ci linter for go code
- go-grpc - includes proto and buf files for generation
- go-docker - includes 2 stage Dockerfile and compose for ease of development
- go-pg - includes pgx module in porstgres, sqlc for generation and goose for migrations
- go-redis - includes redis template
- go-nats - includes consumer and producer nats template

Example:

gen-tools gen drone make gpl

`,
}

var flags = []Flag{}

func Execute() {
	for _, flag := range flags {
		AddFlag(flag)
	}

	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
